"""Add 'comment' column

Revision ID: a86c7deb38ca
Revises: 2e6934191923
Create Date: 2022-02-13 17:43:29.694377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a86c7deb38ca'
down_revision = '2e6934191923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('comment', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'comment')
    # ### end Alembic commands ###
